import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { firefox } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { unzipSync } from '../vendor/fflate.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const server = createServer(async (req, res) => {
  const path = (req.url || '/').split('?')[0].slice(1) || 'index.html';
  if (!['index.html', 'style.css', 'app.js', 'core.js', 'zip-worker.js', 'vendor/fflate.js'].includes(path)) { res.writeHead(404); res.end(); return; }
  res.writeHead(200, { 'Content-Type': path.endsWith('.js') ? 'text/javascript' : path.endsWith('.css') ? 'text/css' : 'text/html' });
  res.end(await readFile(join(root, path)));
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const remote = process.env.PACKCHECK_BASE_URL;
const base = remote || `http://127.0.0.1:${server.address().port}/`;
const output = join(root, 'test-artifacts', remote ? 'live' : 'local');
await mkdir(output, { recursive: true });
const browser = await firefox.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 950 }, acceptDownloads: true });
const page = await context.newPage();
const errors = [];
const external = [];
const audits = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (!request.url().startsWith(base) && !request.url().startsWith('blob:')) external.push(request.url()); });
async function audit(name) {
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze();
  audits.push({ name, violations: result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })) });
  await writeFile(join(output, 'accessibility.json'), JSON.stringify(audits, null, 2));
  assert.deepEqual(audits.at(-1).violations, []);
}
const row = name => page.locator('.file-row').filter({ has: page.locator('.file-original', { hasText: name }) });
try {
  await page.goto(base, { waitUntil: 'networkidle' });
  assert.equal(await page.locator('#build').isDisabled(), true);
  await page.keyboard.press('Tab'); assert.equal(await page.locator('.skip').evaluate(el => el === document.activeElement), true);
  await audit('empty desktop');
  await page.locator('#demo').click();
  assert.equal(await page.locator('.file-row').count(), 4);
  assert.equal(await row('.DS_Store').locator('input[type=checkbox]').isChecked(), false);
  assert.equal(await page.locator('#build').isDisabled(), true);
  await page.screenshot({ path: join(output, 'messy-desktop.png'), fullPage: true });
  await page.locator('#choose-0').selectOption('0');
  await page.getByRole('button', { name: 'Use this path: report.pdf', exact: true }).click();
  await page.locator('#choose-1').selectOption('1');
  await page.getByRole('button', { name: 'Use this path: README.md', exact: true }).click();
  assert.equal(await row('report-final.pdf').locator('.path').inputValue(), 'report.pdf');
  assert.equal(await row('notes.txt').locator('.path').inputValue(), 'README.md');
  assert.equal(await page.locator('#build').isDisabled(), false);
  await row('notes.txt').getByRole('button', { name: /Preview:/ }).click();
  assert.match(await page.locator('#previewText').innerText(), /Fictional A2 submission/);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('#preview').isVisible(), false);
  await row('report-final.pdf').getByRole('button', { name: /Preview:/ }).click();
  assert.match(await page.locator('#openFile').getAttribute('href'), /^blob:/);
  await page.locator('#closePreview').click();
  await page.locator('#limit').fill('0.0001');
  await page.locator('#build').click();
  await page.waitForFunction(() => /over your size limit/.test(document.querySelector('#buildStatus').textContent));
  assert.equal(await page.locator('#ready').isVisible(), false);
  assert.equal(await page.locator('#retryCompression').isVisible(), true);
  await page.locator('#retryCompression').click();
  await page.waitForFunction(() => /over your size limit/.test(document.querySelector('#buildStatus').textContent));
  assert.equal(await page.locator('#compression').inputValue(), '9');
  assert.equal(await page.locator('#retryCompression').isVisible(), false);
  await page.locator('#limit').fill('5');
  await page.locator('#build').click();
  await page.locator('#download').waitFor({ state: 'visible' });
  await audit('ready desktop');
  const downloadEvent = page.waitForEvent('download'); await page.locator('#download').click();
  const download = await downloadEvent;
  assert.equal(download.suggestedFilename(), '123456_A2.zip');
  const entries = unzipSync(new Uint8Array(await readFile(await download.path())));
  assert.deepEqual(Object.keys(entries).sort(), ['README.md', 'report.pdf', 'src/main.py']);
  assert.equal(new TextDecoder().decode(entries['src/main.py']), 'print("PackCheck demo")\n');
  assert.equal(new TextDecoder().decode(entries['README.md']), 'Fictional A2 submission\nRun: python src/main.py\n');
  assert.equal(new TextDecoder().decode(entries['report.pdf']).slice(0, 8), '%PDF-1.4');
  await writeFile(join(output, 'sample-submission.zip'), await readFile(await download.path()));
  const manifestEvent = page.waitForEvent('download'); await page.locator('#manifest').click();
  const manifest = await manifestEvent;
  assert.match(await readFile(await manifest.path(), 'utf8'), /src\/main.py/);
  await page.screenshot({ path: join(output, 'ready-desktop.png'), fullPage: true });
  await page.locator('.package-options summary').click();
  await page.locator('#rootFolder').fill('123_A2');
  assert.equal(await page.locator('#ready').isVisible(), false);
  await page.locator('#build').click(); await page.locator('#download').waitFor({ state: 'visible' });
  const wrappedEvent = page.waitForEvent('download'); await page.locator('#download').click();
  const wrapped = await wrappedEvent;
  const wrappedEntries = unzipSync(new Uint8Array(await readFile(await wrapped.path())));
  assert.deepEqual(Object.keys(wrappedEntries).sort(), ['123_A2/README.md', '123_A2/report.pdf', '123_A2/src/main.py']);
  assert.deepEqual(wrappedEntries['123_A2/report.pdf'], entries['report.pdf']);
  await page.locator('#lang').click();
  assert.match(await page.locator('h1').innerText(), /作业/);
  assert.equal(await row('notes.txt').locator('.path').inputValue(), 'README.md');
  assert.equal(await page.locator('#ready').isVisible(), true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.mobile-package a').click();
  assert.equal(new URL(page.url()).hash, '#package');
  await audit('ready mobile Chinese');
  await page.screenshot({ path: join(output, 'ready-mobile-zh.png'), fullPage: true });
  for (const width of [320, 768]) {
    await page.setViewportSize({ width, height: 900 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `Overflow ${width}`);
  }
  await row('notes.txt').locator('.path').fill('report.pdf');
  assert.equal(await page.locator('#ready').isVisible(), false);
  assert.equal(await page.locator('#build').isDisabled(), true);
  assert.match(await page.locator('#checks').innerText(), /重复/);
  await row('notes.txt').locator('.path').fill('../README.md');
  assert.match(await page.locator('#checks').innerText(), /路径无效/);
  await row('notes.txt').locator('.path').fill('README.md');
  await row('notes.txt').locator('input[type=checkbox]').uncheck();
  assert.match(await page.locator('#checks').innerText(), /缺少必需/);
  await row('notes.txt').locator('input[type=checkbox]').check();
  page.once('dialog', dialog => dialog.dismiss()); await page.locator('#clear').click();
  assert.equal(await page.locator('.file-row').count(), 4);
  page.once('dialog', dialog => dialog.accept()); await page.locator('#clear').click();
  assert.equal(await page.locator('.file-row').count(), 0);
  await page.locator('#lang').click();
  await page.locator('#required').fill(''); await page.locator('#archiveName').fill('real-files.zip');
  await page.locator('#rootFolder').fill('');
  await page.locator('#fileInput').setInputFiles([
    { name: 'hello.txt', mimeType: 'text/plain', buffer: Buffer.from('User-supplied text\n') },
    { name: 'fake.pdf', mimeType: 'application/pdf', buffer: Buffer.from('This is plain text') },
    { name: 'markup.html', mimeType: 'text/html', buffer: Buffer.from('<img src=x onerror="window.injected=true">') }
  ]);
  await page.waitForFunction(() => document.querySelectorAll('.file-row').length === 3);
  assert.match(await page.locator('#checks').innerText(), /Extension does not match/);
  await row('markup.html').getByRole('button', { name: /Preview:/ }).click();
  assert.equal(await page.locator('#previewText img').count(), 0);
  assert.equal(await page.evaluate(() => window.injected), undefined);
  assert.equal(await page.locator('#openFile').getAttribute('download'), 'markup.html');
  await page.keyboard.press('Escape');
  await row('fake.pdf').getByRole('button', { name: /Remove:/ }).click();
  await page.locator('#undo').click();
  assert.equal(await row('fake.pdf').count(), 1);
  await row('fake.pdf').getByRole('button', { name: /Remove:/ }).click();
  await page.locator('#fileInput').setInputFiles({ name: 'hello.txt', mimeType: 'text/plain', buffer: Buffer.from('Second version') });
  await page.waitForFunction(() => document.querySelectorAll('.file-row').length === 3);
  assert.match(await page.locator('#checks').innerText(), /Duplicate output path/);
  await page.locator('.file-row').last().locator('.path').fill('hello-v2.txt');
  assert.equal(await page.locator('#build').isDisabled(), false);
  // An actual directory upload proves folder structure handling rather than a mocked path.
  const fixture = await mkdtemp(join(tmpdir(), 'packcheck-'));
  await mkdir(join(fixture, 'src'));
  await writeFile(join(fixture, 'src', 'entry.py'), 'print("folder")');
  await writeFile(join(fixture, '.DS_Store'), 'metadata');
  await page.locator('#folderInput').setInputFiles(fixture);
  await page.waitForFunction(() => document.querySelectorAll('.file-row').length === 5);
  assert.equal(await row('entry.py').locator('.path').inputValue(), 'src/entry.py');
  assert.equal(await row('.DS_Store').locator('input[type=checkbox]').isChecked(), false);
  await page.locator('#required').fill('source/');
  await page.locator('#choose-0').selectOption(await row('entry.py').getAttribute('data-id'));
  await page.getByRole('button', { name: 'Move into folder: source/', exact: true }).click();
  assert.equal(await row('entry.py').locator('.path').inputValue(), 'source/entry.py');
  await row('entry.py').locator('.path').fill('src/entry.py');
  await page.locator('#required').fill('src/entry.py');
  await page.locator('#build').click(); await page.locator('#download').waitFor({ state: 'visible' });
  const realEvent = page.waitForEvent('download'); await page.locator('#download').click();
  const realDownload = await realEvent;
  const realEntries = unzipSync(new Uint8Array(await readFile(await realDownload.path())));
  assert.equal(new TextDecoder().decode(realEntries['hello.txt']), 'User-supplied text\n');
  assert.equal(new TextDecoder().decode(realEntries['hello-v2.txt']), 'Second version');
  assert.equal(new TextDecoder().decode(realEntries['src/entry.py']), 'print("folder")');
  assert.equal(Object.keys(realEntries).some(name => name.includes('.DS_Store')), false);
  await page.locator('#fileInput').setInputFiles({ name: 'too-big.bin', mimeType: 'application/octet-stream', buffer: Buffer.alloc(21 * 1024 * 1024) });
  await page.waitForFunction(() => /exceeds the prototype limit/.test(document.querySelector('#importStatus').textContent));
  assert.equal(await page.locator('.file-row').count(), 5);
  assert.equal(await page.locator('#ready').isVisible(), true);
  assert.deepEqual(await page.evaluate(() => [localStorage.length, sessionStorage.length]), [0, 0]);
  await page.reload(); assert.equal(await page.locator('.file-row').count(), 0);
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  console.log('PASS PackCheck Firefox: real files/folder, fixes, previews, ZIP bytes, size limit, manifest, language, mobile, content safety, privacy, accessibility');
  console.log(`Artifacts: ${output}`);
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
